name: Checkov
description: Executes Checkov Security Scan


runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
    #- uses: actions/checkout@v3

    # Add resulting output to PR
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        framework: terraform
        output_format: sarif
        output_file_path: results.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: results.sarif

    - name: Checkov GitHub Action on PR
      id: checkov
      if: github.event_name == 'pull_request'
      uses: bridgecrewio/checkov-action@v12
      with:
        framework: terraform
        output_format: cli

    - name: Update Pull Request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ github.token }}
        script: |
          const output = `#### Checkov Test ${{ steps.checkov.outcome }}

          <details><summary>Checkov Results</summary>

          ${{ steps.checkov.outputs.results }}

          </details>

          *Triggered by: @${{ github.actor }}, Action: ${{ github.event_name }}`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
