name: "Checkov"
run-name: Scheduled Checkov
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: write
jobs:
  checkov:
    name: checkov

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - uses: actions/checkout@v3

      # Run checkov
      - name: checkov scan
        uses: ./.github/actions/checkov
