name: "Auto Plan"
run-name: Auto Plan triggered by @${{ github.actor }} - ${{ github.event_name }}
on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches: ["main"]

jobs:
  # This workflow contains a single job called "scan"
  scan:
    name: checkov
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      issues: write
      pull-requests: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - uses: actions/checkout@v3

      # Run checkov
      - name: checkov scan
        uses: ./.github/actions/checkov


  plan:
    name: plan
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
      deployments: write
    needs: ["scan"]
    uses: ./.github/workflows/plan.yml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}
    concurrency: ${{ matrix.environment }}
    with:
      ENVIRONMENT_NAME: ${{ matrix.environment }}
      ROLE_DURATION_SECONDS: 3600
    secrets: inherit
